name: BuildWindows

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/build_assets.yml

  buildWin64:
    needs: buildAssets
    runs-on: windows-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v4
